format_version: v1.0
type: UniqueComponent
attributes: {id: sysNetPic32mzw1}
children:
- type: Symbols
  children:
  - type: Menu
    attributes: {id: SYS_NET_APPDEBUG_FLOW_CONFIG_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: String
    attributes: {id: SYS_NET_APPDEBUG_PRESTR}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: String
    attributes: {id: SYS_NET_HOST_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 192.168.43.192}
  - type: Combo
    attributes: {id: SYS_NET_IPPROT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: UDP}
  - type: Integer
    attributes: {id: SYS_NET_PORT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4444'}
- type: ElementPosition
  attributes: {x: '115', y: '133', id: sysNetPic32mzw1}
