format_version: v1.0
type: GroupComponent
attributes: {displayName: System Configuration, id: System Configuration}
children:
- type: ElementPosition
  attributes: {x: '310', y: '60', id: System Configuration}
