format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipStack}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: TCPIP_STACK_CALLOC_FUNC}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: calloc}
  - type: Integer
    attributes: {id: TCPIP_STACK_DRAM_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: '65000'}
  - type: String
    attributes: {id: TCPIP_STACK_FREE_FUNC}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: free}
  - type: Integer
    attributes: {id: TCPIP_STACK_HEAP_SIZE_RECOMMEND}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: '29'}
  - type: Boolean
    attributes: {id: TCPIP_STACK_INTERFACE_CHANGE_SIGNALING}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: TCPIP_STACK_MALLOC_FUNC}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: malloc}
  - type: Boolean
    attributes: {id: TCPIP_STACK_SYS_RANDOM_H2_ADAPTER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_STACK_USER_NOTIFICATION}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: 'true'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: Core_SysConsole_Dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sys_console_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: sys_console}
- type: ElementPosition
  attributes: {x: '30', y: '560', id: tcpipStack}
