format_version: v1.0
type: UniqueComponent
attributes: {id: drv_ba414e}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: DRV_BA414E_SYS_RTOS_TASK}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
- type: ElementPosition
  attributes: {x: '450', y: '100', id: drv_ba414e}
