format_version: v1.0
type: UniqueComponent
attributes: {id: sysWifiProvPic32mzw1}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: SYS_WIFIPROV_CUSTOM_HTTP_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: SYS_WIFIPROV_HTTP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiProvPic32mzw1, value: 'true'}
      - type: User
        attributes: {value: 'true'}
  - type: File
    attributes: {id: SYS_WIFIPROV_HTTP_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: SYS_WIFIPROV_MPFS_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '20', y: '20', id: sysWifiProvPic32mzw1}
