configName: pic32mz_w1_eth_wifi_freertos
folderName: pic32mz_w1_curiosity_freertos
format_version: v1.0
frameworkPath: ..\..\H3_bitbucket
processor: PIC32MZ1025W104132
projectName: pic32mz_w1_curiosity_freertos
settings:
  PackageFilter: bootloader;bootloader_apps_uart;bsp;core;core_apps_pic32mz_w1;crypto;cryptoauthlib;csp;csp_apps_pic32mz_w1;dev_packs;net;quick_docs;touch;usb;wireless_apps_pic32mzw1_wfi32e01;wireless_apps_winc1500;wireless_apps_winc3400;wireless_system_pic32mzw1_wfi32e01;wireless_wifi
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-W_DFP\1.5.203\atdf\PIC32MZ1025W104132.atdf
