format_version: v1.0
type: GroupComponent
attributes: {displayName: System Configuration, id: System Configuration}
children:
- type: ElementPosition
  attributes: {x: '389', y: '59', id: System Configuration}
