format_version: v1.0
type: UniqueComponent
attributes: {id: sysWifiPic32mzw1}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: SYS_WIFI_RTOS_DELAY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: '4'}
- type: ElementPosition
  attributes: {x: '480', y: '19', id: sysWifiPic32mzw1}
