configName: pic32mz_w1_curiosity_driver
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MZ1025W104132
projectName: ''
settings:
  PackageFilter: bsp;core;core_apps_pic32mz_w1;crypto;cryptoauthlib;csp;csp_apps_pic32mz_w1;dev_packs;net;quick_docs;usb;wireless_apps_pic32mzw1_wfi32e01;wireless_apps_pic32mzw1_wfi32e01_old;wireless_system_pic32mzw1_wfi32e01;wireless_system_pic32mzw1_wfi32e01_last;wireless_system_pic32mzw1_wfi32e01_old;wireless_wifi
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-W_DFP\1.5.203\atdf\PIC32MZ1025W104132.atdf
