format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipStack}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: TCPIP_STACK_CALLOC_FUNC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: calloc}
  - type: Boolean
    attributes: {id: TCPIP_STACK_DRAM_DEBUG_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Integer
    attributes: {id: TCPIP_STACK_DRAM_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '80000'}
  - type: String
    attributes: {id: TCPIP_STACK_FREE_FUNC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: free}
  - type: Integer
    attributes: {id: TCPIP_STACK_HEAP_SIZE_RECOMMEND}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: '35'}
  - type: String
    attributes: {id: TCPIP_STACK_MALLOC_FUNC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: malloc}
  - type: Integer
    attributes: {id: TCPIP_STACK_SECURE_PORT_ENTRIES}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '15'}
  - type: Boolean
    attributes: {id: TCPIP_STACK_SYS_RANDOM_H2_ADAPTER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_STACK_USER_NOTIFICATION}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '240', y: '20', id: tcpipStack}
