format_version: v1.0
type: UniqueComponent
attributes: {id: net_Pres}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: NET_PRES_BLOB_CERT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: '1'}
  - type: Boolean
    attributes: {id: NET_PRES_BLOB_CERT_REPO}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: 'false'}
  - type: Boolean
    attributes: {id: NET_PRES_CERT_STORE_STUBS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_GENERATE_ENC_STUBS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: 'true'}
  - type: Integer
    attributes: {id: NET_PRES_RTOS_STACK_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: '20480'}
  - type: Boolean
    attributes: {id: NET_PRES_SUPPORT_DATAGRAM}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_SUPPORT_ENCRYPTION}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: NET_PRES_SUPPORT_STREAM}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_USE_WOLF_SSL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: 'false'}
- type: ElementPosition
  attributes: {x: '20', y: '20', id: net_Pres}
