format_version: v1.0
type: UniqueComponent
attributes: {id: tmr2}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: TCON_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '112'}
  - type: Integer
    attributes: {id: TIMER_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '390625'}
  - type: Long
    attributes: {id: TIMER_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '116'}
  - type: KeyValueSet
    attributes: {id: TIMER_PRE_SCALER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: '0'}
  - type: Float
    attributes: {id: TIMER_TIME_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '167.7696'}
  - type: Boolean
    attributes: {id: TMR_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: 'true'}
  - type: Integer
    attributes: {id: TMR_PRESCALER_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '256'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: TMR2_TMR}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: lib_qtouch}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: Touch_timer}
- type: ElementPosition
  attributes: {x: '110', y: '168', id: tmr2}
