format_version: v1.0
type: UniqueComponent
attributes: {id: sysWifiPic32mzw1}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SYS_WIFI_APPDEBUG_CFG_FLOW}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: SYS_WIFI_APPDEBUG_CONNECT_FLOW}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: SYS_WIFI_APPDEBUG_DBG_LEVEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: SYS_WIFI_APPDEBUG_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: SYS_WIFI_APPDEBUG_ERR_LEVEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Menu
    attributes: {id: SYS_WIFI_APPDEBUG_FLOW_CONFIG_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: SYS_WIFI_APPDEBUG_FUNC_LEVEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: SYS_WIFI_APPDEBUG_INFO_LEVEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Menu
    attributes: {id: SYS_WIFI_APPDEBUG_LEVEL_CONFIG_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: String
    attributes: {id: SYS_WIFI_APPDEBUG_PRESTR}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: SYS_WIFI_APPDEBUG_PROVISIONINGCMD_FLOW}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: SYS_WIFI_APPDEBUG_PROVISIONINGSOCK_FLOW}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: SYS_WIFI_APPDEBUG_PROVISIONING_FLOW}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: SYS_WIFI_AP_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: SYS_WIFI_AP_SSIDVISIBILE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
- type: ElementPosition
  attributes: {x: '480', y: '20', id: sysWifiPic32mzw1}
